apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-standalone.fullname" . }}
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongodb-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb-standalone.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mongodb-standalone.fullname" . }}
                key: mongodb-password
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mongodb-standalone.fullname" . }}
                key: mongodb-root-password
          - name: MONGODB_DATABASE
            value: {{ .Values.database.name}}
          - name: MONGODB_USERNAME
            value: {{ .Values.database.username}}
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - db.adminCommand('ping')
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - db.adminCommand('ping')
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mongodb-standalone.fullname" . }}