apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
  name: {{ include "mongodb-standalone.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName}}
  {{- end }}
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
