apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-standalone.fullname" . }}
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
data:
  mongodb-password: bWFuYWdl
  mongodb-root-password: MjczTGhUUFZjaw==
type: Opaque
