apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-standalone.fullname" . }}
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mongodb-standalone.selectorLabels" . | nindent 4 }}