apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-standalone.fullname" . }}
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
data:
  mongodb-password: {{ .Values.database.password | b64enc | quote}}
  mongodb-root-password: {{ .Values.database.rootPassword | b64enc | quote}}
type: Opaque
